spacetelescope/stenv

.github/workflows/build.yml, tests/test_import.py
[<img width="1208" alt="image" src="https://user-images.githubusercontent.com/16024299/180489717-f2e8f25f-f18b-41c5-adbf-cb00ed69a892.png">](https://github.com/zacharyburnett/spacetelescope-env-distribution/actions/runs/2720044637)
=> add more OS and Python versions to the matrix

.github/workflows/build.yml
Putting the import validation step in a separate dependent job in the workflow prevents the testing packages (`pytest-xdist`, `ci-watson`, etc.) from being included in the exported environment file.
=> add slow tests, separate import validation, and strip builds from exported file

.github/workflows/build.yml, stenv-dev.yml, stenv-latest.yml, stenv-stable.yml
related to https://github.com/asdf-format/asdf/pull/1171; when `asdf 2.12.1` is released, this PR can be merged
=> pin `asdf` to newest patch version to fix dependency for newest `jsonschema` release

.github/workflows/build.yml
change from specific version pins of GitHub Actions to be general major version tags (maintained by the individual authors) instead.
=> unpin action tags

.github/workflows/build.yml
`micromamba` is a `conda` client rewritten as a single C++ application; this makes it **much** faster than using `miniconda`. Using it in place of `miniconda` seems to significantly speed up the environment creation and caching process in the CI: whereas `miniconda` took between 1.5 and 11 minutes to provision an environment, `micromamba` takes between 15 and 50 seconds.
The current issue is that `micromamba` appears to have an issue with `env export` in that it doesn't show `pip` packages; I've opened an issue here: https://github.com/mamba-org/mamba/issues/2008; in the meantime, I've kept the `export` step only to use `miniconda` to export the YAML files.
=> use mamba to build environment

docs/source/index.rst
This change unhides the table of contents on the main page of the documentation, as the navigation index is hidden by default on smaller screens
from email suggestion:
```
hi Nadia,
thanks very much!! That level of detail is indeed be sufficient. However 
I had completely missed this because initially the "Getting started" 
link was not appearing for me since the left-hand menu was not expanding 
given my browser window width -- so I only saw the very simple page, see 
attached screenshot.
When I made my browser window wider, I now see the "Getting started" 
link on the left, and when I click on that, indeed it has the level of 
detail needed.
However, this does reveal a problem with the "feature" on readthedocs 
that a page won't auto-expand the left-hand menu unless it's wide 
enough. …
```
=> unhide TOC tree on start page

.github/workflows/build.yml
stores environment variables in a `.txt` file to pass along to jobs, and uses a `sed` command that can work on both BSD and GNU versions (using `sed -i"" -e "s/old/new/g"` syntax)
=> consolidate environment variables

environment.yml
add `astropy`, `numpy`, and `scipy` to the environment definitions (they existed in the environment but were not in the definition)
=> add explicit references to large scientific packages that are already in the environment

docs/source/developer_notes.rst, docs/source/faq.rst, docs/source/getting_started.rst
these instructions should improve readability in the case where a user's `conda create` command fails; it adds a note and a link to the relevant FAQ question with instructions to use the `environment.yaml` file to resolve the environment from scratch.
docs built at https://stenv--91.org.readthedocs.build/en/91/
=> add reference to fallback instructions to use unconstrained environment file

environment.yaml
The current JWST release does not include reference data for the updates to `stcal` and `stdatamodels`; this PR should be ready when JWST has a new release
=> remove pins

docs/source/getting_started.rst
I helped walk a student through this process today. There were points where a tempting copy-and-paste-able command did not apply to their system (i.e. it was for macOS and not Linux, and it didn't point to the latest version). I think any command that looks like it can be copied and pasted unmodified eventually will be, so I changed the steps to be the "shortcut" path of just giving a URL to conda and letting it go. The Readthedocs theme also cuts off the end of the commands and it's not always obvious the box will scroll, so the student was missing that `--name` was an important option to include.
Happy to iterate on this if you're not happy with it as written or explain my changes further if you want. Just trying to smooth over some bumps in the road I noticed with them earlier today. …
=> Update getting started guide

docs/rtd_environment.yaml, docs/source/conf.py, docs/source/developer_notes.rst, docs/source/faq.rst, docs/source/getting_started.rst
add explicit instructions to run `conda init` when installing `conda` (in response to https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=a0df4b2d47ee71d0289c4f32736d438f%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)
=> add instructions on how to run `conda init` and also include tab option for `mamba` commands

docs/source/developer_notes.rst, docs/source/faq.rst, docs/source/getting_started.rst
```
conda create -n stenv -f
```
->
```
conda env create -n stenv -f
```
=> fix create examples to include `env`

.github/workflows/build.yaml
using the `version` never really made much sense, especially since the updates to environment dependencies are disassociated from the Git ref
=> use current date in filename

.github/workflows/build.yaml, .github/workflows/test.yaml, environment.yaml
currently, the environment will not build with Python 3.12 because of `scipy`:
https://github.com/spacetelescope/stenv/actions/runs/7672163531/job/20912084061#step:3:992
```
../meson.build:85:2: ERROR: Problem encountered: Your Python version is too new. SciPy 1.9 supports Python 3.8-3.11; if you are trying to build from source for the most recent SciPy version you may hit this error as well. Please build from the `main` branch on GitHub instead.
```
I'll keep this PR in draft until that changes
=> drop Python 3.9 and add Python 3.12

.github/workflows/build.yaml, .github/workflows/test.yaml
it appears that `macos-latest`, having previously pointed to an Intel-based X86_64 macOS runner (`macos-13`), now points to an M1 AMR64 macOS runner (`macos-14`). As we still need to build and deliver `stenv` for Intel hardware, I have updated the workflows matrices to use `macos-13` and `macos-latest`
=> change matrix and use `macos-13` for Intel hardware

docs/source/developer_notes.rst, docs/source/faq.rst, docs/source/getting_started.rst
in response to the Anaconda ToS changes:
https://legal.anaconda.com/policies/en/#:~:text=2.1%20Organizational%20Use.%C2%A0
> 2.1 Organizational Use.  Your registration, download, use, installation, access, or enjoyment of all Anaconda Offerings on behalf of an organization that has two hundred (200) or more employees or contractors ("Organizational Use") requires a paid license. For sake of clarity, use by government entities and nonprofit entities with over 200 employees or contractors is considered Organizational Use.  Educational Entities will be exempt from the paid license requirement, provided that the use of the Anaconda Offering(s) is solely limited to being used for a curriculum-based course. Anaconda reserves the right to monitor the registration, download, use, installation, …
=> update docs to indicate that `micromamba` and `mamba` are recommended over `conda`

.github/workflows/test.yaml
```
=========================== short test summary info ============================
FAILED tests/hap/test_pipeline.py::TestSingleton::test_astrometric_singleton[iaaua1n4q] - TypeError: download_crds() takes 1 positional argument but 2 were given
FAILED tests/hap/test_svm_ibyt50.py::test_svm_point_total_cat - NameError: name 'expected_point_sources' is not defined
FAILED tests/hap/test_svm_ibyt50.py::test_svm_segment_total_cat - NameError: name 'expected_segment_sources' is not defined
= 3 failed, 47 passed, 74 skipped, 2 xfailed, 2317 warnings in 810.85s (0:13:30) =
```
```
ImportError while loading conftest '/home/runner/work/stenv/stenv/stistools/tests/conftest.py'.
tests/conftest.py:7: in <module>
from astropy.tests.helper import enable_deprecations_as_exceptions
E   ImportError: …
```
=> run tests for `drizzlepac`, `stistools`, and `stsynphot`

.github/workflows/build.yaml, .github/workflows/label_pull_request.yaml, .github/workflows/test.yaml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
=> MNT: Use hash for Action workflow versions and update if needed

.github/workflows/test.yaml, environment.yaml
from @rizeladiaz:
> Pysynphot   is the engine of the HST ETC, so I would say that we need to have it available until we migrate all HST ETC to pandeia and we improve on the new Synphot documentation.
=> remove `pysynphot` from environment
